### ISSUE TITLE
Release archives contain binary in path

### ISSUE THREAD

**Issue by makii42** [gabrielcsapo/lcov-server#30]
The archives on the release page, e.g. [the macOS version 1.2.4](https://github.com/gabrielcsapo/lcov-server/releases/download/1.2.4/lcov-server-macos.tgz) contain the binary in a relative path, as you see here:

```
$ curl -sSL -o lcov-server-macos.tgz https://github.com/gabrielcsapo/lcov-server/releases/download/1.2.4/lcov-server-macos.tgz
$ tar tzf ./lcov-server-macos.tgz 
Users/gabrielcsapo/Documents/lcov-server/packed/lcov-server-macos
$ 
```

As the binary is only one file, couldn't the release just be the gzipped binary?

**Comment by gabrielcsapo** [comment]
I have updated https://github.com/gabrielcsapo/lcov-server/releases/tag/1.2.4 without the full paths.
